package Vista;

import Conexion.Connect;
import java.sql.Connection;

public class JFFondo extends javax.swing.JFrame {
    private Connection cn;
    public JFFondo() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(this.MAXIMIZED_BOTH);

    }
    public JFFondo(Connection cn) {
        initComponents();
        
        this.setTitle("Fondo");
        this.setLocationRelativeTo(this);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.cn=cn;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMITablaU = new javax.swing.JMenuItem();
        jMITablaA = new javax.swing.JMenuItem();
        jMITablaT = new javax.swing.JMenuItem();
        jMITablaP = new javax.swing.JMenuItem();
        jMITablaS = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tablas");

        jMITablaU.setText("Tabla Usuario");
        jMITablaU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITablaUActionPerformed(evt);
            }
        });
        jMenu4.add(jMITablaU);

        jMITablaA.setText("Tabla Asiento");
        jMITablaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITablaAActionPerformed(evt);
            }
        });
        jMenu4.add(jMITablaA);

        jMITablaT.setText("Tabla Ticket");
        jMITablaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITablaTActionPerformed(evt);
            }
        });
        jMenu4.add(jMITablaT);

        jMITablaP.setText("Tabla Película");
        jMITablaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITablaPActionPerformed(evt);
            }
        });
        jMenu4.add(jMITablaP);

        jMITablaS.setText("Tabla Sala");
        jMITablaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITablaSActionPerformed(evt);
            }
        });
        jMenu4.add(jMITablaS);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMITablaUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITablaUActionPerformed

        JFTablaUsuario jftablaU = new JFTablaUsuario(cn);
        jftablaU.setVisible(true);
    }//GEN-LAST:event_jMITablaUActionPerformed

    private void jMITablaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITablaAActionPerformed

        JFTablaAsiento jftablaA = new JFTablaAsiento(cn);
        jftablaA.setVisible(true);
    }//GEN-LAST:event_jMITablaAActionPerformed

    private void jMITablaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITablaTActionPerformed
        JFTablaTicket jftablaT = new JFTablaTicket(cn);
        jftablaT.setVisible(true);
    }//GEN-LAST:event_jMITablaTActionPerformed

    private void jMITablaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITablaPActionPerformed
        JFTablaPelicula jftablaP = new JFTablaPelicula(cn);
        jftablaP.setVisible(true);
    }//GEN-LAST:event_jMITablaPActionPerformed

    private void jMITablaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITablaSActionPerformed
        JFTablaSala jftablaS = new JFTablaSala(cn);
        jftablaS.setVisible(true);
    }//GEN-LAST:event_jMITablaSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFondo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMITablaA;
    private javax.swing.JMenuItem jMITablaP;
    private javax.swing.JMenuItem jMITablaS;
    private javax.swing.JMenuItem jMITablaT;
    private javax.swing.JMenuItem jMITablaU;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
